### ISSUE TITLE
Ability to edit bookmarks/outline

### ISSUE THREAD

**Issue by sachko** [junrrein/pdfslicer#131]
this feature is present in the PDF mod program, i wonder if it can be copied to this program as PDF mod is outdated

**Comment by junrrein** [comment]
Hi there.

I've historically been opposed to this since I don't want Slicer becoming complex, but either way the library we use for handling PDF files (QPDF) can't edit bookmarks.

Looking at the open-source C++ libraries for PDF files, it seems that only Podofo is able to add/edit outlines of a document. Unfortunately I've tried using Podofo in the past, and copying pages from some specific files resulted in a crash. I may try using it again at a later date.

**Comment by amivaleo** [comment]
Hi man!

For such scope, I suggest you to use this: https://github.com/arrufat/pdftag

**Comment by junrrein** [comment]
@amivaleo

It seems that pdftag doesn't have the ability to manage bookmarks.

**Comment by amivaleo** [comment]
> @amivaleo
> 
> It seems that pdftag doesn't have the ability to manage bookmarks.

Apologies, I read "bookmarks" but my mind understood "tags". 😶

**Comment by AlisterH** [comment]
There's always jpdfbookmarks.

**Comment by junrrein** [comment]
@AlisterH Thanks for the suggestion.

**Comment by junrrein** [comment]
Ultimately, I'm not planning to support bookmark edition in Slicer. This decision can be revisited in the future.
