### ISSUE TITLE
Enable access to network shares

### ISSUE THREAD

**Issue by tronta** [junrrein/pdfslicer#160]
Currently one can only open and save to the local file system.
Network shares are not displayed.
It would be really great if those could be used.

**Comment by junrrein** [comment]
Hi there, and thanks for the report! I agree that this should work.

Until I fix this, you can try the workaround at https://github.com/celluloid-player/celluloid/issues/396#issuecomment-494363191 for the time being.

**Comment by junrrein** [comment]
I have made a build with a possible fix for this bug. Could you please test it?

You can find it at https://github.com/flathub/com.github.junrrein.PDFSlicer/pull/31#issuecomment-591752662

**Comment by tronta** [comment]
thanks you very much. I see only the networks which have been mounted already in "other places" and then I can also open and save them.
But I do not see the bookmarks for network shares and I cannot add them as bookmarks.

**Comment by junrrein** [comment]
From https://github.com/flathub/com.github.junrrein.PDFSlicer/pull/31#issuecomment-596119824:

> Thanks for your effort, but I don't see a difference between this version and the version before.

I merged the partial fix anyway, since it seems it's the best I'll be able to do.

From https://github.com/flatpak/xdg-desktop-portal/issues/102, I can see that network mounts access isn't something that's cleanly implemented in Flatpak. So until that gets done, I won't be able to do more, so I'm closing this issue for now.

If you hear of another project that found a way to work around this problem, feel free to reopen this issue.
