### ISSUE TITLE
Extra empty space in the "save as" and "open file" dialogs

### ISSUE THREAD

**Issue by amivaleo** [junrrein/pdfslicer#165]
Hi!

I'm definitely finicky, I know that.

Open slicer and click on the "open" button.

OR

Edit a pdf in slicer and then click on the "save as" button.

-> a dialog appears in which there's this extra space:

![Schermata da 2020-03-24 11-38-06](https://user-images.githubusercontent.com/24316547/77416757-96d85900-6dc4-11ea-8e88-cfd02503def8.png)

That extra space also affects the dialog which is shown after clicking on the "+" button.

That space disappears as soon as you click on any item in that dialog.

Can you please get rid of that? 😋

Thanks!

**Comment by junrrein** [comment]
Hi there!

> I'm definitely finicky, I know that.

Most people, when hitting an issue like this, just shrug their shoulders and move on. But you took time out of your day to let me know, so thanks! I haven't noticed this bug.

It seems this is actually an issue with Flatpak/GtkFileChooserNative, since I can't replicate the issue when running Slicer straight from the compiled sources, but I can with the version installed from Flathub. And I also can replicate this with Firefox, which I didn't know also uses GtkFileChooserNative.

I've filed a bug report with upstream: https://github.com/flatpak/xdg-desktop-portal-gtk/issues/288

Thanks again!

**Comment by amivaleo** [comment]
Well... I'm italian, I'm in lockdown due to the pandemic.

I've sooo much time now. 😄

> I've filed a bug report

Ty :)

**Comment by junrrein** [comment]
> Well... I'm italian, I'm in lockdown due to the pandemic.

Oh shit, I didn't put two and two together before. I already knew you were Italian. :stuck_out_tongue:

In Argentina we are also in lockdown for the same reason. Stay safe!
