### ISSUE TITLE
"Open read-only file" <- what does it do?

### ISSUE THREAD

**Issue by amivaleo** [junrrein/pdfslicer#191]
Hi!

In the bottom left of the open-file-dialog in Slicer you can read "Open read-only file" (or something like that, I'm translating from my Slicer which is localized in my language). It's a check-box.

![Schermata da 2020-05-10 12-46-46](https://user-images.githubusercontent.com/24316547/81497065-583b2700-92bc-11ea-854a-f8f12adb3543.png)

What happens when I check it? I see no differences.

**Comment by junrrein** [comment]
Hey there,

This only happens when using the Flatpaked Slicer. When compiling and running from source, a standard Gtk dialog is shown.

It seems it's a Flatpak feature, allowing you control to whether apps can modify the files you give them, but I can't find documentation for this feature anywhere.

Anyway, it doesn't make a difference because in Slicer opened files are always used in a read-only mode.
