### ISSUE TITLE
Support custom page numbering

### ISSUE THREAD

**Issue by sojusnik** [junrrein/pdfslicer#33]
Some pdfs don't start with page one – they have a custom page number (also called page label). At the moment under every pdf page `pdfslicer` shows the page number. By double-clicking on it we could change it, if this would be implemented.

**Comment by junrrein** [comment]
The thing is, Slicer doesn't take page label metadata into account when it comes to saving files.

Preserving page labels/numbers brings another question: what page numbers do be use when deleting a range of pages from the start or middle of the document? Because if we use the original numbers, then the result would be a document where some page numbers are "missing". I don't know if I'm coming across clearly here.

**Comment by sojusnik** [comment]
The following page numbers should always be oriented on the first page number, f.i.:

You have a pdf with 6 pages, but decide that the first page is actually the 31st. You rename it accordingly, so the other pages turn to (31), 32, 33, 34, 35, 36. Then you realize that page 34 is not necessary at all – you remove it. As a result page 35 turns into 34, page 36 into 35.

**Comment by junrrein** [comment]
Sorry, but I don't want Slicer to have this kind of feature. I would rather have the app stay as a simple "Split and merge PDFs" tool.

Anyway, I want to thank you for all of your suggestions, I appreciate them.
