### ISSUE TITLE
pdfslicer store copy from input & output PDF files after each process taking by this extra space for no thing !!

### ISSUE THREAD

**Issue by Nokia808** [junrrein/pdfslicer#73]
Hi. I noticed that your application store a copy of PDF input file & output PDF file in unusual paths inspite saving output PDF file in other location !! Why this !! It will take extra space of my disk for no thing !

Let me explain:
1) I opened an input PDF file located on my desktop called "test.pdf"
2) I made process (delete some pages) on test.pdf
3) I saved output file on my desktop ALSO as "Untitled Document"

But I doscoved that I have on my disk copy of "test.pdf" (the input PDF) stored at:
/run/user/1000/doc/df0c07dc
while there is also a copy from output PDF "Untitled Document" soted at:
/run/user/1000/doc/cf0a70fd

This is very bad ! This will lead to eat extra space for no thing !
If it is mandatory to make such copies to complete processes then you should make them only temporal (be automatically deleted after complete processses of PDF manipulations).

Best

**Comment by Nokia808** [comment]
Not only these 2 paths I described above ! But also other paths ! See bellow screenshots:

![2](https://user-images.githubusercontent.com/25375330/56722476-b12e3080-6736-11e9-92eb-e3d89a67259d.png)

![3](https://user-images.githubusercontent.com/25375330/56722493-b7bca800-6736-11e9-98fe-5222a86216f7.png)

Why all these folders & copies created multiple times for each process & not deleted automatically ?!

Also see these multiple folders at higher level:

![1](https://user-images.githubusercontent.com/25375330/56722625-04a07e80-6737-11e9-8a05-d597bfa7ec8b.png)

**Comment by junrrein** [comment]
Thanks for the report!

Those files aren't actually consuming extra space, but I understand the confusion, so here's an explanation.

Flatpak doesn't allow an application direct access to the user's filesystem. When Slicer wants to open or save a file, Slicer invokes the File-Chooser Portal (indirecly, via Gtk). The way this portal works is by exposing only the specific file Slicer wants to read or write via a virtual filesystem. This virtual filesystem points, in turn, to the real files we are reading and writing. No file copies are made in this process.

You can read the (sparse) documentation for this portal [here](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.FileChooser).

On the other hand, Slicer does make a copy of the files it opens, before opening them. The reason is to avoid bugs when saving and overwriting the original file. These copied files are copied at a Slicer-specific `/tmp` file that is only accessible by Flatpak. When closing Slicer, these files get deleted automatically.

Cheers!

**Comment by Nokia808** [comment]
@junrrein 

Hi. You said "When closing Slicer, these files get deleted automatically"
Are you sure ?! PDF copies that appeared in my screenshots after I already closed application after complete processes ......

**Comment by junrrein** [comment]
I wasn't clear enough. There are two cases:

Case 1:

> Flatpak doesn't allow an application direct access to the user's filesystem. When Slicer wants to open or save a file, Slicer invokes the File-Chooser Portal (indirecly, via Gtk). The way this portal works is by exposing only the specific file Slicer wants to read or write via a virtual filesystem. This virtual filesystem points, in turn, to the real files we are reading and writing. No file copies are made in this process.

This case is the one you can see in your screenshots. Those "files" don't actually use extra space, despite what your file manager may tell you.

Case 2:

> On the other hand, Slicer does make a copy of the files it opens, before opening them. The reason is to avoid bugs when saving and overwriting the original file. These copied files are copied at a Slicer-specific /tmp directory that is only accessible by Flatpak. When closing Slicer, these files get deleted automatically.

You can't see this case in your screenshots.
