### ISSUE TITLE
Change the selection method

### ISSUE THREAD

**Issue by junrrein** [junrrein/pdfslicer#85]
From https://github.com/junrrein/pdfslicer/issues/30#issuecomment-489116521:

> the selection method should be exactly the same as that used by nautilus -> this sets to 0 the effort required for the user in order to learn how to select pages in Slicer and, as a bonus, sets to 0 the effort of Julian who won't need to reinvent the wheel! :)

**Comment by junrrein** [comment]
@amivaleo 

The selection method used to be the one you described, until [version 1.3](https://github.com/junrrein/pdfslicer/releases/tag/v1.3.0). So why was it changed? I found out about the ["Selection mode"](https://developer.gnome.org/hig/stable/selection-mode.html.en) UI pattern, from the Gnome HIG, and I decided to implement it in Slicer.

Slicer is a little different from other apps that implement this UI pattern, in the sense that the "selection mode" is activated all of the time, since that's the only way it makes sense in this app's context.

It was my impression that Nautilus was going to implement this UI pattern too, but it seems it only aims to use an [action bar](https://gitlab.gnome.org/GNOME/nautilus/issues/322) in the future.

I have a couple of problems with using "traditional selection" (this is how I'm going to refer to it from now on):

* You need to hold `Ctrl` to select multiple pages.

    Since selecting pages is the main use of left-clicking on thumbnails, having to hold down a key for this is a nuisance.

* It's easy to lose the current selection.

    It's related to the previous point. If you forget to hold the `Ctrl` key, or you somehow mispress it, you are going to lose the selection. It's especially frustrating if it happens in a document with a lot of pages.

Keep in mind that multiple-page selection using `Shift` is implemented, but it's not the Gtk implementation, so if you find any bugs with it you can report them.

One thing that I do agree on is that selected pages don't pop-out enough, but I think #84 should take care of that.

With all of this being said, what do you think?

**Comment by amivaleo** [comment]
Uhm...

In general, I believe that "the best" is to follow as much as possible the general UX of the environment. If you know that nautilus will slightly change its UX (and thus, I guess this will happen to the other applications too), then I'm totally fine with your choice. I mean: I believe that you're doing the right thing from some "objective point of view".

What I don't like of the current UI is the fact that it's hard to spot which page is selected, because of the missing blue background. The UX is already good, except for some tweaks like #80 :)

My advice is to follow the UX used on other apps. It should be the easiest thing to do from the code point of view, I suppose, and it minimizes the efforts for the users, who only need to learn one way of doing things that works for all applications. If this is your idea, then there's no "issue" on this matter. ;)

**Comment by junrrein** [comment]
Closing since I'm not going to do any changes in this area for now.
