### ISSUE TITLE
Use a different icon for the "Big preview" button

### ISSUE THREAD

**Issue by junrrein** [junrrein/pdfslicer#86]
From https://github.com/junrrein/pdfslicer/issues/30#issuecomment-489116521:

> the print-button on each page should be removed. It triggers the action "show me a preview". I believe that such action should also be triggered by a text-based button on the bottom toolbar. This button should only appear when only one page is selected. It should be hidden (not only grayed out). The action itself should be triggered by pressing the space key (just like in nautilus...).

**Comment by junrrein** [comment]
@amivaleo 

Showing a big preview of a page is intended for those cases where the user isn't sure if a page should be part of a selection. Having the ability to discern this without having to lose the current selection is an important part.

Relegating this action to a button in the bottom toolbar that can only be activated when there is a single page selected wouldn't serve this purpose.

The current implementation of this idea does have a problem: it doesn't work on touch-controlled devices.

If you can think up another alternative that accommodates  the use-case I have in mind, I'll be glad to hear it.

**Comment by amivaleo** [comment]
> the user isn't sure if a page should be part of a selection [...] discern this without having to lose the current selection

Ah-ha! I didn't think about this possibility.

It's hard to find an alternative maybe. You want the user to be able to _select_ a page to get its preview, while not losing the current _selection_. In other words, there's the need for two selection methods. 🤔

I have no useful ideas right now. The only thing I'm thinking for the current gui is to change the icon from that lens+printer to a lens only ("system-search-symbolic").

I must be honest: I question this feature. I think that the maximum zoom level is more than enough to see a quite big thumbnail of all the pages. So that you don't really need to open the preview of any of them. I also believe that this zoom-approach doesn't break any cointinuity in what you're doing, respect to the preview-approach. I am not aware of similar preview-features in other apps either.

What do you think about that? I mean: is it so mandatory to have such feature? 🤔

**Comment by amivaleo** [comment]
So...
I see you really like this preview! :D

All in all, it can stay. But I suggest to remove the overlay zoom-buttons and replace the with a set a buttons like in eog.

![Schermata da 2019-07-24 09-43-04](https://user-images.githubusercontent.com/24316547/61774593-769c6880-adf7-11e9-8a35-84da753e9d70.png)


The only extra I'd like to suggest is to use a slider in the popover menu that appears if you click on the number in the middle.

**Comment by junrrein** [comment]
@amivaleo 

Hey there, you hit the nail on the head lol.

Since this report was created I've been watching my usage patterns with Slicer and I noticed I tend to use the smallest zoom factor, and then using the preview if I want to be sure about a specific page. That's why I don't want to remove it.

So, let's go over the proposed changes.

> (...) But I suggest to remove the overlay zoom-buttons and replace them with a set a buttons like in eog.
> 
> ![Schermata da 2019-07-24 09-43-04](https://user-images.githubusercontent.com/24316547/61774593-769c6880-adf7-11e9-8a35-84da753e9d70.png)
>
> The only extra I'd like to suggest is to use a slider in the popover menu that appears if you click on the number in the middle.

This could be done, but it would make more sense once Slicer supports continous zoom adjustment. I'll track that at #125.

Then there is one of the changes that were proposed originally:

> The only thing I'm thinking for the current gui is to change the icon from that lens+printer to a lens only ("system-search-symbolic").

That's the one I'm committing on doing for now.
