### ISSUE TITLE
Re-add Windows support

### ISSUE THREAD

**Issue by Lvaskz** [junrrein/pdfslicer#90]
Hi, same question
why did you remove windows support? I was using it in my version of windows.
Will be available some day?

**Comment by junrrein** [comment]
Hi there,

Windows support was removed because I changed the library I used to save documents, and my distribution doesn't provide a ready-made Windows binary for it. You can still download [the last version that supported Windows here](https://github.com/junrrein/pdfslicer/releases/tag/v1.5.5).

I should be able to compile the library myself, but since there are so many free apps similar to Slicer for Windows, it hasn't been a priority.

**Comment by junrrein** [comment]
Windows support was re-added in [version 1.8.8](https://github.com/junrrein/pdfslicer/releases/tag/v1.8.8). Enjoy!

**Comment by Lvaskz** [comment]
> Windows support was re-added in [version 1.8.8](https://github.com/junrrein/pdfslicer/releases/tag/v1.8.8). Enjoy!

Thanks !!!!!
